### ISSUE TITLE
Implementation Clarification for Formtrack

### ISSUE THREAD

**Issue by david-spsgc** [formspark/formtrack#5]
After adding datatrack to the form, the session parameters are not being reported after submission. There should be greater clarity  about how to add the code.

Ex: should the user define input types?

  <input type="hidden" class="abcd" name="utm_source" value="source_value_here">
  <input type="hidden" class="abcd" name="utm_medium" value="medium_value_here">
  <input type="hidden" class="abcd" name="utm_campaign" value="campaign_value_here">
  <input type="hidden" class="abcd" name="utm_term" value="term_value_here">
  <input type="hidden" class="abcd" name="utm_content" value="content_value_here">

Or should they remain blank since the documentation says:
"Formtrack will now automatically inject the supported parameters into your HTML form submissions."

**Comment by botre** [comment]
Hello,

No additional setup is needed, as per the documentation.

I just saw your email and tested your website's contact form using the referrer parameter in the URL. It worked.

Please keep in mind that the parameter needs to be included in your URL when the user reaches your contact form.

Best regards
